- name: Tasks
  block:
    - name: Create app directory
      ansible.builtin.file:
        mode: "0755"
        path: "{{ web_app_dir }}"
        state: directory

    - name: Copy docker-compose template
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ web_app_dir }}/docker-compose.yml"
        mode: "0644"
  tags: deploy

- name: Start the app
  block:
    - name: Ensure docker started
      ansible.builtin.service:
        name: "docker"
        state: "started"
        enabled: true

    - name: Run image
      community.docker.docker_compose_v2:
        project_src: "{{ web_app_dir }}"
        state: "present"
        remove_orphans: true
  tags: deploy


- name: Wipe
  when: web_app_full_wipe is defined and web_app_full_wipe
  ansible.builtin.import_tasks:
    file: 0-wipe.yml
  tags: wipe