- name: Install python3 and pip
  apt:
    name:
      - python3
      - python3-pip

- name: Install Docker
  import_tasks: install_docker.yml

- name: Install Docker Compose
  import_tasks: install_compose.yml